-- JuriLegal All-in-One Kanzlei-Dashboard Schema
-- Applied: 2026-03-25

-- Subscription Tiers
CREATE TABLE IF NOT EXISTS subscription_tiers (id text PRIMARY KEY, name text NOT NULL, price_monthly numeric(10,2) DEFAULT 0, features jsonb DEFAULT '[]', stripe_price_id text);
INSERT INTO subscription_tiers (id,name,price_monthly) VALUES ('basic','JuriLegal Basic',0),('all-in-one','JuriLegal All-in-One',149.00) ON CONFLICT DO NOTHING;

-- Subscriptions
CREATE TABLE IF NOT EXISTS subscriptions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES profiles(id), tier_id text NOT NULL REFERENCES subscription_tiers(id) DEFAULT 'basic', status text DEFAULT 'active', stripe_subscription_id text, avv_signed_at timestamptz, avv_document_path text, is_early_adopter boolean DEFAULT false, current_period_start timestamptz, current_period_end timestamptz, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS early_adopters (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid UNIQUE NOT NULL REFERENCES profiles(id), created_at timestamptz DEFAULT now());

-- Kanzlei Core
CREATE TABLE IF NOT EXISTS cases (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES profiles(id), reference_number text, title text NOT NULL, description text, status text DEFAULT 'open', case_type text, court text, opponent_name text, opponent_lawyer text, client_id uuid, value_in_dispute numeric(12,2), tags jsonb DEFAULT '[]', notes text, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS kanzlei_clients (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES profiles(id), client_type text DEFAULT 'private', first_name text, last_name text, company_name text, email text, phone text, address text, city text, zip text, notes text, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS case_documents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), case_id uuid NOT NULL REFERENCES cases(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES profiles(id), title text NOT NULL, file_path text NOT NULL, original_filename text, mime_type text, file_size integer, version integer DEFAULT 1, tags jsonb DEFAULT '[]', notes text, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS deadlines (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), case_id uuid REFERENCES cases(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES profiles(id), title text NOT NULL, due_date date NOT NULL, reminder_date date, priority text DEFAULT 'normal', completed boolean DEFAULT false, completed_at timestamptz, notes text, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS kanzlei_tasks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), case_id uuid REFERENCES cases(id) ON DELETE SET NULL, user_id uuid NOT NULL REFERENCES profiles(id), title text NOT NULL, description text, status text DEFAULT 'open', priority text DEFAULT 'normal', due_date date, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS time_entries (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), case_id uuid REFERENCES cases(id) ON DELETE SET NULL, user_id uuid NOT NULL REFERENCES profiles(id), description text NOT NULL, duration_minutes integer NOT NULL, hourly_rate numeric(8,2), date date DEFAULT CURRENT_DATE, billable boolean DEFAULT true, invoiced boolean DEFAULT false, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS kanzlei_invoices (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), case_id uuid REFERENCES cases(id), user_id uuid NOT NULL REFERENCES profiles(id), client_id uuid REFERENCES kanzlei_clients(id), invoice_number text, total_amount numeric(12,2), tax_amount numeric(12,2), status text DEFAULT 'draft', pdf_path text, billing_type text DEFAULT 'hourly', items jsonb DEFAULT '[]', created_at timestamptz DEFAULT now());

-- Integrations
CREATE TABLE IF NOT EXISTS legal_research_queries (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES profiles(id), query text NOT NULL, filters jsonb, result_count integer, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS bea_messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES profiles(id), case_id uuid REFERENCES cases(id), direction text NOT NULL, sender text, recipient text, subject text, body text, attachments jsonb DEFAULT '[]', bea_message_id text, status text DEFAULT 'draft', created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS migration_jobs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES profiles(id), source_system text NOT NULL, status text DEFAULT 'pending', progress integer DEFAULT 0, total_items integer DEFAULT 0, migrated_items integer DEFAULT 0, error_count integer DEFAULT 0, errors jsonb DEFAULT '[]', field_mapping jsonb, report jsonb, started_at timestamptz, completed_at timestamptz, created_at timestamptz DEFAULT now());
